/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentaApp.java
 *
 * Created on 09/11/2012, 02:18:20 PM
 */
package com.app;

import com.entidades.Articulo;
import com.entidades.CompraCab;
import com.entidades.CompraDet;
import com.entidades.Funcionario;
import com.entidades.Proveedor;
import com.entidades.Tipo;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import util.HibernateUtil;

/**
 *
 * @author Ariel
 */
public class CompraApp extends javax.swing.JDialog {

    /** Creates new form VentaApp */
    public CompraApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//Centra formulario
        hibernateSession();//Método para abrir una Session de Hibernate.
        arranque();//Meto para limpiar y habilitar campos.
    }
    private DefaultTableModel model;//Variable para manejar el DefaultTableModel.
    private Session st;//Variable para almacenar la Session de Hibernate.
    private int var,idArtt,numCompra;//Variables de clase auxiliares necesarias.

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idProv = new javax.swing.JTextField();
        desProv = new javax.swing.JTextField();
        dirProv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        can = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        desArt = new javax.swing.JComboBox();
        btnPresentacion = new org.edisoncor.gui.button.ButtonSeven();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalGeneral = new javax.swing.JTextField();
        nuevo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        idArt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compras");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Funcionarios"));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombres:");

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });

        nombres.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Apellidos:");

        apellidos.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(apellidos))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 100, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Proveedor"));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Descripción");

        idProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idProvKeyPressed(evt);
            }
        });

        desProv.setEditable(false);

        dirProv.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Dirección");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(idProv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(desProv, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dirProv, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dirProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 390, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Articulo"));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Descripcion");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Precio de Compra:");

        pco.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Disponibles:");

        can.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Cantidad:");

        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Total:");

        total.setEditable(false);

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel22.setText("Q.");

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel23.setText("Q.");

        desArt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPresentacion.setBackground(new java.awt.Color(0, 204, 0));
        btnPresentacion.setText("+ Producto");
        btnPresentacion.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        btnPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(desArt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pco, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desArt)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(btnPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 780, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Precio de Compra", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 760, 110));

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Trashcan_empty.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eliminar.setContentAreaFilled(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 70, 70));

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Select.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregar.setContentAreaFilled(false);
        agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 70, 70));

        fecha.setEditable(false);
        fecha.setForeground(new java.awt.Color(0, 51, 153));
        fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fecha.setEnabled(false);
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 150, 20));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Fecha:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 10));

        num.setEditable(false);
        num.setForeground(new java.awt.Color(0, 51, 153));
        num.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num.setEnabled(false);
        jPanel1.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("No. Compra:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        hora.setEditable(false);
        hora.setForeground(new java.awt.Color(0, 51, 153));
        hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hora.setEnabled(false);
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 120, 20));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Hora:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 10));

        totalGeneral.setEditable(false);
        totalGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalGeneral.setForeground(new java.awt.Color(0, 0, 102));
        totalGeneral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(totalGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 160, 40));

        nuevo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New-file-icon-3.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nuevo.setContentAreaFilled(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 60, 60));

        cancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/delete-file-icon.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelar.setContentAreaFilled(false);
        cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 60, 60));

        guardar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save-icon.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        guardar.setContentAreaFilled(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 60, 60));

        panelNice1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel17.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/principal.png"))); // NOI18N
        jLabel17.setText("Principal");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/ventas_1.png"))); // NOI18N
        jLabel18.setText("Ventas");

        jLabel19.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/inventario.png"))); // NOI18N
        jLabel19.setText("Inventario");

        jLabel20.setFont(new java.awt.Font("Gurmukhi Sangam MN", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/compras_1.png"))); // NOI18N
        jLabel20.setText("Compras");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logotitulo.png"))); // NOI18N

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(7, 7, 7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(7, 7, 7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        panelNice1.add(panelCurves1, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 450));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel24.setText("Q.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText("Total esta compra:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, -1));

        idArt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idArtKeyPressed(evt);
            }
        });
        jPanel1.add(idArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 17));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        nuevo();// Evento ActionPerformed para botón nuevo.
    }//GEN-LAST:event_nuevoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        arranque();// Evento ActionPerformed para botón cancelar.
    }//GEN-LAST:event_cancelarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
       agregar();// Evento ActionPerformed para botón agregar.
        
    }//GEN-LAST:event_agregarActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "id".
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            buscarFuncionario();
        }
    }//GEN-LAST:event_idKeyPressed

    private void idProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idProvKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "idClie".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarProveedor();
        }
    }//GEN-LAST:event_idProvKeyPressed

    private void idArtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idArtKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "idArt".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarArticulo();
        }
    }//GEN-LAST:event_idArtKeyPressed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "cantidad".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            calcularParcial();
        }
    }//GEN-LAST:event_cantidadKeyPressed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();// Evento ActionPerformed para botón eliminar.
    }//GEN-LAST:event_eliminarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();// Evento ActionPerformed para botón guardar.
    }//GEN-LAST:event_guardarActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void btnPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPresentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CompraApp dialog = new CompraApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField apellidos;
    private org.edisoncor.gui.button.ButtonSeven btnPresentacion;
    private javax.swing.JTextField can;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox desArt;
    private javax.swing.JTextField desProv;
    private javax.swing.JTextField dirProv;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField hora;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idArt;
    private javax.swing.JTextField idProv;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombres;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField num;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private javax.swing.JTextField pco;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalGeneral;
    // End of variables declaration//GEN-END:variables
public void hibernateSession(){
    //Abrimos una session y la guardamos en una variable de clase.
    st = HibernateUtil.getSessionFactory().openSession();
}
public void arranque(){
    //Configuramos objetos para el arranque.
    cargarCombo();
    this.nuevo.setEnabled(true);
    this.jPanel2.setVisible(false);
    this.id.setText("0");
    this.nombres.setText("Lester");
    this.apellidos.setText("Meneses");
    this.agregar.setEnabled(false);
    this.eliminar.setEnabled(false);
    this.guardar.setEnabled(false);
    this.num.setText(null);
    this.fecha.setText(null);
    this.hora.setText(null);
    this.id.setText(null);
    this.id.setEnabled(false);
    this.nombres.setText(null);
    this.apellidos.setText(null);
    this.idProv.setText(null);
    this.idProv.setEnabled(false);
    this.dirProv.setText(null);
    this.idArt.setText(null);
    this.idArt.setEnabled(false);
    this.desArt.setSelectedIndex(-1);
    this.pco.setText(null);
    this.can.setText(null);
    this.cantidad.setText(null);
    this.cantidad.setEnabled(false);
    this.total.setText(null);
    this.totalGeneral.setText(null);
    tableModel();
}
public void cargarCombo(){
    this.desArt.removeAllItems();
    List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
    for(Articulo articuloList : lista){
        this.desArt.addItem(articuloList.getDes());            
    }
}

public void tableModel(){
    //Configuramos el jTable utilizando DefaultTableModel
    this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
    this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
    this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
    model = (DefaultTableModel)this.jTable1.getModel();
    model.setNumRows(0);
}
public void nuevo(){
    //Configuramos acciones, habilitamos campos al precionar el botón nuevo
    obtenetID();
    this.id.setEnabled(true);
    this.idProv.setEnabled(true);
    this.idArt.setEnabled(true);
    this.cantidad.setEnabled(true);
    this.agregar.setEnabled(true);
    this.eliminar.setEnabled(true);
    this.guardar.setEnabled(true);
    this.nuevo.setEnabled(false);
    this.id.requestFocus();
    Calendar cal = Calendar.getInstance();
    String calString = retornarString(cal);
    String calHora = retornarStringHora(cal);
    this.fecha.setText(calString);
    this.num.setText(String.valueOf(numCompra));    
    this.hora.setText(calHora);
}
public void obtenetID(){
    //Utilizamos el método siguiente para conseguir en número de compra...
    //correspondiente
    numCompra = 0;
    List<CompraCab> lista = (List<CompraCab>)st.createQuery("From CompraCab").list();
    for (Iterator<CompraCab> it = lista.iterator(); it.hasNext();) {
        CompraCab compraCab = it.next();
        numCompra = compraCab.getNum() + 1;
    }
    if(numCompra==0){
        numCompra=1;
    } 
}
public void buscarArticulo(){
    //Utilizamos el método siguiente para buscar artículos por el "ID",
    //este método se llama desde un evento KeyPressed.
    int idArti = 0;
    try {
        try {
           idArti = Integer.parseInt(this.idArt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
        Articulo art = (Articulo)st.load(Articulo.class, idArti);
       // this.desArt.setText(art.getDes());
        this.pco.setText(String.valueOf(art.getPco()));
        this.can.setText(String.valueOf(art.getCan()));
        this.cantidad.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay artículo con ID: " + idArti);
    }    
}
public void calcularParcial(){
    //Lo siguiente nos permite calcular el total para cada artículo,
    //esto tomando en cuenta total de compra y precio de compra.
    int canCompra = 0;
    int pCompra = 0;
    int totalParcial = 0 ;
    try {
        canCompra = Integer.parseInt(this.cantidad.getText());
        pCompra = Integer.parseInt(this.pco.getText());       
           totalParcial = canCompra * pCompra;
           this.total.setText(String.valueOf(totalParcial)); 
           this.agregar.requestFocus();
           
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Se requiere datos numérico.");
    }
}
public void buscarFuncionario(){
    //Utilizamos el método siguiente para buscar funcionario por el "ID",
    //este método se llama desde un evento KeyPressed.
    int idFunc = 0;
    try {
        try {
           idFunc = Integer.parseInt(this.id.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
         Funcionario funcio = (Funcionario)st.load(Funcionario.class, idFunc);
         this.nombres.setText(funcio.getNombres());
         this.apellidos.setText(funcio.getApellidos());
         this.idProv.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay funcionario con ID: " + idFunc);
    }    
}
public void buscarProveedor(){
    //Utilizamos el método siguiente para buscar proveedor por el "ID",
    //este método se llama desde un evento KeyPressed.
    int idPrv = 0;
    try {
        try {
           idPrv = Integer.parseInt(this.idProv.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
         Proveedor proveedor = (Proveedor)st.load(Proveedor.class, idPrv);
         this.desProv.setText(proveedor.getDes());
         this.dirProv.setText(proveedor.getDir());
         this.idArt.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay proveedor con ID: " + idPrv);
    }    
}
public void agregar(){
    //Método llamado desde el botón agregar, primeramente comprobamos que los datos sean correctos,
    //que los campos no esten vacios, que no se repitan datos.
    if(this.id.getText().isEmpty()){
        //JOptionPane.showMessageDialog(null, "Seleccione un funcionario.");
        this.id.setText("0"); 
    }
    else{
        if(this.idProv.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione un cliente.");
        }
        else{
            if(this.idArt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Seleccione un articulo.");
            }
            else{
                if(this.cantidad.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Indique una cantidad.");
                }
                else{
                    verificar();
                    if(var>=1){
                        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Artículo ya Agregado. Desea sumar la cantidad.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
                        if(showConfirmDialog==0){
                           sumarRepetido(); 
                           calcular();
                           confimAgregar();
                           limpiar();
                        }
                        else{
                            limpiar();
                            this.idArt.requestFocus();
                        }
                    }
                    else{
                            model.addRow(new Object[]{
                            //this.idArt.getText(),this.desArt.getText(),this.pco.getText(),this.cantidad.getText(),this.total.getText()
                            });                    
                            calcular();
                            confimAgregar();
                            limpiar(); 
                    }
                    
                }
            }
        }
    }
}
public void confimAgregar(){
    //Método que pregunta al usuario si desea agregar más artículo a la lista.
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Agregar más Articulos.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 0){
            this.idArt.requestFocus();
        }
        else{
            this.guardar.requestFocus();
        }
        
}
public void limpiar(){
    //Limpia campo de datos..
    this.idArt.setText(null);
    this.desArt.removeAllItems();
    this.pco.setText(null);
    this.can.setText(null);
    this.cantidad.setText(null);
    this.total.setText(null);
    this.id.setEnabled(false);
    this.idProv.setEnabled(true);
    this.desProv.setText(null);
    
}
public void calcular(){
    //Método para calcular el total de la compra, obteniendo datos del jtable.
    int totalG = 0;
    for (int i = 0; i < this.jTable1.getRowCount(); i++) {
        Object valueAt = model.getValueAt(i, 4);
        totalG += Integer.parseInt(valueAt.toString());
    }
    this.totalGeneral.setText(String.valueOf(totalG));
}
public void verificar(){
    //Método para verificar que no se duplique el mismo artículo en la tabla,
    //para ello se comprueba el id del artículo.
    var = 0;
    int idAr = Integer.parseInt(this.idArt.getText());
    if(this.jTable1.getRowCount()>=1){
        for (int i = 0; i < this.jTable1.getRowCount(); i++) {
            Object valueAt = model.getValueAt(i, 0);
            int parseInt = Integer.parseInt(valueAt.toString());
            if(idAr == parseInt){
                var = 1;
                idArtt = i;
            }        
        }        
    }  
}
public void sumarRepetido(){
        //Si se repite el ingreso de un artículo específico,se puede obtar por sumar la cantidad de compra,
        //este método localizar el id del artículo específico y aumenta la cantidad de la
        //compra sumandola.
        int artCant = Integer.parseInt(this.cantidad.getText());
        int artTotal = Integer.parseInt(this.total.getText());
        Object valueAt = model.getValueAt(idArtt, 3);
        Object valueAt1 = model.getValueAt(idArtt, 4);
        int cantArt = Integer.parseInt(valueAt.toString());
        int totalArt = Integer.parseInt(valueAt1.toString());
        int x = artCant + cantArt;
        int y = artTotal + totalArt;
            model.setValueAt(x, idArtt, 3);
            model.setValueAt(y, idArtt, 4);        
}

public String retornarString(Calendar fecha){
        //Médodo que se le para un objeto calendar y la combierte en formato String-Fecha
        String retorno=null;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (fecha != null) {
        retorno = sdf.format(fecha.getTime());
        }
        return retorno;
}
public String retornarStringHora(Calendar fecha){
        //Médodo que se le para un objeto calendar y la combierte en formato String-hora
        String retorno=null;
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        if (fecha != null) {
        retorno = sdf.format(fecha.getTime());
        }
        return retorno;
}    
public Calendar retornarCalendar(String fecha){
        //Se le pasa como argumento un String-Fecha y la combierte en objeto calendar.
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();    
        try {
            cal.setTime(sdf.parse(fecha));
        } catch (ParseException ex) {
          JOptionPane.showMessageDialog(null, "Error; compruebe formato de fecha: " + ex);  
        }
        return cal;
    }
public void eliminar(){
    //Permite al usuario seleccionar una fila específica de la table y eliminarla.
    if(this.jTable1.getSelectedRow()==-1){
      JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila de la tabla.");  
    }
    else{
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminar fila seleccionada.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 0){
            int sel = this.jTable1.getSelectedRow();
            model.removeRow(sel);
            this.idArt.requestFocus();
        }
        else{
            this.idArt.requestFocus();
        }
    }
}
public void guardar(){
    //Metodo que nos permite almacenar los datos intruducidos en la base de datos,
    //los datos se guardan en la tabla CompraCab y CompraDet.
    //la primera almacena la cabecera de compra y la segunda los detalles.
    if(this.id.getText().isEmpty() ||this.idProv.getText().isEmpty() ){
        JOptionPane.showMessageDialog(null, "Faltan datos para guardar. Verifique.");
    }
    else{
        if(this.jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No hay datos para guardar.");
        }
        else{
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Desea guardar esta compra.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
            if(showConfirmDialog == 0){
                try {
                    st.beginTransaction();
                    CompraCab compra = new CompraCab();
                    int idFun = Integer.parseInt(this.id.getText());
                    int idPrv = Integer.parseInt(this.idProv.getText());
                    long totalCompra = Long.parseLong(this.totalGeneral.getText());
                    Funcionario funcionario = (Funcionario)st.load(Funcionario.class, idFun);
                    Proveedor proveedor = (Proveedor)st.load(Proveedor.class, idPrv);
                    Calendar fechaCompra = retornarCalendar(this.fecha.getText());
                    String horaCompra = this.hora.getText();
                    compra.setNum(Integer.valueOf(this.num.getText()));
                    compra.setProveedor(proveedor);
                    compra.setFuncionario(funcionario);
                    compra.setFecha(fechaCompra);
                    compra.setHora(horaCompra);
                    compra.setTotal(totalCompra);
                    funcionario.getCompraCabs().add(compra);
                    proveedor.getCompraCabs().add(compra);
                    int rowCount = this.jTable1.getRowCount();
                    int[] idArti = new int[rowCount];
                    int[] cantCompra = new int[rowCount];
                    for (int i = 0; i < this.jTable1.getRowCount(); i++) {
                        CompraDet detalleCompra = new CompraDet();
                        int idArticulo = Integer.parseInt(String.valueOf(model.getValueAt(i, 0)));
                        idArti[i] = idArticulo;
                        Articulo ventaArticulo = (Articulo)st.load(Articulo.class, idArticulo);
                        int cantidadCompra = Integer.parseInt(String.valueOf(model.getValueAt(i, 3)));
                        cantCompra[i]= cantidadCompra;
                        int importeVenta = Integer.parseInt(String.valueOf(model.getValueAt(i, 4)));
                        detalleCompra.setArticulo(ventaArticulo);
                        detalleCompra.setCantidad(cantidadCompra);
                        detalleCompra.setImporte(importeVenta);
                        detalleCompra.setCabecera(compra);
                        compra.getCompraDets().add(detalleCompra);
                    }
                    st.save(compra);
                    st.getTransaction().commit();
                    for (int i = 0; i < idArti.length; i++) {
                        actualizarStrock(cantCompra[i], idArti[i]);
                    }
                    arranque();
                    JOptionPane.showMessageDialog(null, "Compra guardada correctamente.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error guardando compra. Verifique.");
                }
                
            }
            else{                
                this.idArt.requestFocus();
            }
            
        }
    }
}
public void actualizarStrock(int cantidadCompra, int idArticulo){
    //Despúes que el proceso de guardado se de de forma correcta, 
    //se actualizar el stock de los artículos comprados.
    st.beginTransaction();
    Articulo actualizar = (Articulo)st.load(Articulo.class, idArticulo);
    int temp = actualizar.getCan() + cantidadCompra;
    actualizar.setCan(temp);
    st.update(actualizar);
    st.getTransaction().commit();
}
}
