/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentaApp.java
 *
 * Created on 09/11/2012, 02:18:20 PM
 */
package com.app;

import com.entidades.Articulo;
import com.entidades.Cliente;
import com.entidades.Funcionario;
import com.entidades.VentaCab;
import com.entidades.VentaDet;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import util.HibernateUtil;

/**
 *
 * @author Ariel
 */
public class VentaApp extends javax.swing.JDialog {

    /** Creates new form VentaApp */
    public VentaApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        hibernateSession();
        arranque();
    }
    private DefaultTableModel model;
    private Session st;
    private int var,idArtt,numVenta;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idClie = new javax.swing.JTextField();
        des = new javax.swing.JTextField();
        ruc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idArt = new javax.swing.JTextField();
        desArt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pve = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        can = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalGeneral = new javax.swing.JTextField();
        nuevo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Funcionarios"));

        jLabel2.setText("ID");

        jLabel3.setText("Nombres");

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });

        nombres.setEditable(false);

        jLabel8.setText("Apellidos");

        apellidos.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(121, 121, 121))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 50, 60));
        jPanel2.getAccessibleContext().setAccessibleName("Datos Proveedor");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Cliente"));

        jLabel4.setText("ID");

        jLabel5.setText("Nombre");

        idClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idClieKeyPressed(evt);
            }
        });

        des.setEditable(false);

        ruc.setEditable(false);

        jLabel7.setText("Apellido");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(idClie, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 460, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Articulo"));

        jLabel6.setText("ID");

        jLabel9.setText("Descripcion");

        idArt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idArtKeyPressed(evt);
            }
        });

        desArt.setEditable(false);

        jLabel12.setText("Precio de Venta");

        pve.setEditable(false);

        jLabel14.setText("Stock");

        can.setEditable(false);

        jLabel15.setText("Cantidad");

        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });

        jLabel16.setText("Total");

        total.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idArt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desArt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pve, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cantidad)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(desArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 610, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Precio Venta", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 800, 110));

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Trashcan_empty.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eliminar.setContentAreaFilled(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 70, 70));

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Select.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregar.setContentAreaFilled(false);
        agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 70, 70));

        fecha.setEditable(false);
        fecha.setForeground(new java.awt.Color(0, 51, 153));
        fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 80, 20));

        jLabel10.setText("Fecha");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, 10));

        num.setEditable(false);
        num.setForeground(new java.awt.Color(0, 51, 153));
        num.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 130, 20));

        jLabel11.setText("Número de orden");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, 10));

        hora.setEditable(false);
        hora.setForeground(new java.awt.Color(0, 51, 153));
        hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 80, 20));

        jLabel13.setText("Hora");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, 10));

        totalGeneral.setEditable(false);
        totalGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalGeneral.setForeground(new java.awt.Color(0, 0, 102));
        totalGeneral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(totalGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 160, 50));

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nuevo.setContentAreaFilled(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 70, 60));

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cancel32.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelar.setContentAreaFilled(false);
        cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 70, 60));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        guardar.setContentAreaFilled(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 70, 60));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel22.setText("Nueva Venta");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel21.setText("Busque el producto que desea vender, utilice los filtros de busqueda para mayor facilidad");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        panelNice1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel17.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/principal.png"))); // NOI18N
        jLabel17.setText("Principal");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/compras_1.png"))); // NOI18N
        jLabel18.setText("Compras");

        jLabel19.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/inventario.png"))); // NOI18N
        jLabel19.setText("Inventario");

        jLabel20.setFont(new java.awt.Font("Gurmukhi Sangam MN", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/ventas_1.png"))); // NOI18N
        jLabel20.setText("Ventas");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logotitulo.png"))); // NOI18N

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        panelNice1.add(panelCurves1, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        nuevo();// Evento ActionPerformed para botón nuevo.
    }//GEN-LAST:event_nuevoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        arranque();// Evento ActionPerformed para botón cancelar.
    }//GEN-LAST:event_cancelarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
       agregar();// Evento ActionPerformed para botón agregar.
        
    }//GEN-LAST:event_agregarActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "id".
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            buscarFuncionario();
        }
    }//GEN-LAST:event_idKeyPressed

    private void idClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClieKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "idClie".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarCliente();
        }
    }//GEN-LAST:event_idClieKeyPressed

    private void idArtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idArtKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "idArt".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarArticulo();
        }
    }//GEN-LAST:event_idArtKeyPressed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        //Uso del Evento KeyPressed dentro del campo de texto "cantidad".
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            calcularParcial();
        }
    }//GEN-LAST:event_cantidadKeyPressed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();// Evento ActionPerformed para botón eliminar.
    }//GEN-LAST:event_eliminarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();// Evento ActionPerformed para botón guardar.
    }//GEN-LAST:event_guardarActionPerformed

    private void totalGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalGeneralActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                VentaApp dialog = new VentaApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField can;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField des;
    private javax.swing.JTextField desArt;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField hora;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idArt;
    private javax.swing.JTextField idClie;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombres;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField num;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private javax.swing.JTextField pve;
    private javax.swing.JTextField ruc;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalGeneral;
    // End of variables declaration//GEN-END:variables
public void hibernateSession(){
    st = HibernateUtil.getSessionFactory().openSession();
}
public void arranque(){
    this.nuevo.setEnabled(true);
    this.agregar.setEnabled(false);
    this.eliminar.setEnabled(false);
    this.guardar.setEnabled(false);
    this.num.setText(null);
    this.fecha.setText(null);
    this.hora.setText(null);
    this.id.setText(null);
    this.id.setEnabled(false);
    this.nombres.setText(null);
    this.apellidos.setText(null);
    this.idClie.setText(null);
    this.idClie.setEnabled(false);
    this.des.setText(null);
    this.idArt.setText(null);
    this.idArt.setEnabled(false);
    this.desArt.setText(null);
    this.pve.setText(null);
    this.can.setText(null);
    this.cantidad.setText(null);
    this.cantidad.setEnabled(false);
    this.total.setText(null);
    this.totalGeneral.setText(null);
    tableModel();
}
public void tableModel(){
    this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
    this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
    this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
    model = (DefaultTableModel)this.jTable1.getModel();
    model.setNumRows(0);
}
public void nuevo(){
    obtenetID();
    this.id.setEnabled(true);
    this.idClie.setEnabled(true);
    this.idArt.setEnabled(true);
    this.cantidad.setEnabled(true);
    this.agregar.setEnabled(true);
    this.eliminar.setEnabled(true);
    this.guardar.setEnabled(true);
    this.nuevo.setEnabled(false);
    this.id.requestFocus();
    Calendar cal = Calendar.getInstance();
    String calString = retornarString(cal);
    String calHora = retornarStringHora(cal);
    this.fecha.setText(calString);
    this.num.setText(String.valueOf(numVenta));    
    this.hora.setText(calHora);
}
public void obtenetID(){
    numVenta = 0;
    List<VentaCab> lista = (List<VentaCab>)st.createQuery("From VentaCab").list();
    for (Iterator<VentaCab> it = lista.iterator(); it.hasNext();) {
        VentaCab ventaCab = it.next();
        numVenta = ventaCab.getNum() + 1;
    }
    if(numVenta==0){
        numVenta=1;
    } 
}
public void buscarArticulo(){
    int idArti = 0;
    try {
        try {
           idArti = Integer.parseInt(this.idArt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
        Articulo art = (Articulo)st.load(Articulo.class, idArti);
        this.desArt.setText(art.getDes());
        this.pve.setText(String.valueOf(art.getPve()));
        this.can.setText(String.valueOf(art.getCan()));
        this.cantidad.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay artículo con ID: " + idArti);
    }    
}
public void calcularParcial(){
    int canVent = 0;
    int pVenta = 0;
    int stock = 0;
    int totalParcial = 0 ;
    try {
        canVent = Integer.parseInt(this.cantidad.getText());
        pVenta = Integer.parseInt(this.pve.getText());
        stock = Integer.parseInt(this.can.getText());
        if(stock < canVent){
             JOptionPane.showMessageDialog(null, "Stock insuficiente.");
        }
        else{
           totalParcial = canVent * pVenta;
           this.total.setText(String.valueOf(totalParcial)); 
           this.agregar.requestFocus();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Se requiere datos numérico.");
    }
}
public void buscarFuncionario(){
    int idFunc = 0;
    try {
        try {
           idFunc = Integer.parseInt(this.id.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
         Funcionario funcio = (Funcionario)st.load(Funcionario.class, idFunc);
         this.nombres.setText(funcio.getNombres());
         this.apellidos.setText(funcio.getApellidos());
         this.idClie.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay funcionario con ID: " + idFunc);
    }    
}
public void buscarCliente(){
    int idCl = 0;
    try {
        try {
           idCl = Integer.parseInt(this.idClie.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico.");
        }
         Cliente clie = (Cliente)st.load(Cliente.class, idCl);
         this.des.setText(clie.getDes());
         this.ruc.setText(clie.getRuc());
         this.idArt.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No hay cliente con ID: " + idCl);
    }    
}
public void agregar(){
    if(this.id.getText().isEmpty()){
        //JOptionPane.showMessageDialog(null, "Seleccione un funcionario.");
        this.id.setText("0");
    }
    else{
        if(this.idClie.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione un cliente.");
        }
        else{
            if(this.idArt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Seleccione un articulo.");
            }
            else{
                if(this.cantidad.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Indique una cantidad.");
                }
                else{
                    verificar();
                    if(var>=1){
                        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Artículo ya Agregado. Desea sumar la cantidad.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
                        if(showConfirmDialog==0){
                           sumarRepetido(); 
                           calcular();
                           confimAgregar();
                           limpiar();
                        }
                        else{
                            limpiar();
                            this.idArt.requestFocus();
                        }
                    }
                    else{
                            model.addRow(new Object[]{
                            this.idArt.getText(),this.desArt.getText(),this.pve.getText(),this.cantidad.getText(),this.total.getText()
                            });                    
                            calcular();
                            confimAgregar();
                            limpiar(); 
                    }
                    
                }
            }
        }
    }
}
public void confimAgregar(){
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Agregar más Articulos.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 0){
            this.idArt.requestFocus();
        }
        else{
            this.guardar.requestFocus();
        }
        
}
public void limpiar(){
    this.idArt.setText(null);
    this.desArt.setText(null);
    this.pve.setText(null);
    this.can.setText(null);
    this.cantidad.setText(null);
    this.total.setText(null);
    this.id.setEnabled(false);
    this.idClie.setEnabled(false);
}
public void calcular(){
    int totalG = 0;
    for (int i = 0; i < this.jTable1.getRowCount(); i++) {
        Object valueAt = model.getValueAt(i, 4);
        totalG += Integer.parseInt(valueAt.toString());
    }
    this.totalGeneral.setText(String.valueOf(totalG));
}
public void verificar(){
    var = 0;
    int idAr = Integer.parseInt(this.idArt.getText());
    if(this.jTable1.getRowCount()>=1){
        for (int i = 0; i < this.jTable1.getRowCount(); i++) {
        Object valueAt = model.getValueAt(i, 0);
        int parseInt = Integer.parseInt(valueAt.toString());
        if(idAr == parseInt){
            var = 1;
            idArtt = i;
        }        
        }        
    }  
}
public void sumarRepetido(){
        int artCant = Integer.parseInt(this.cantidad.getText());
        int artTotal = Integer.parseInt(this.total.getText());
        Object valueAt = model.getValueAt(idArtt, 3);
        Object valueAt1 = model.getValueAt(idArtt, 4);
        int cantArt = Integer.parseInt(valueAt.toString());
        int totalArt = Integer.parseInt(valueAt1.toString());
        int x = artCant + cantArt;
        int y = artTotal + totalArt;
        int t = Integer.parseInt(this.can.getText());
        if(t>=x){
            model.setValueAt(x, idArtt, 3);
            model.setValueAt(y, idArtt, 4);
        }
        else{
           JOptionPane.showMessageDialog(null, "Stock de artículos insuficiente."); 
        }
        
}

public String retornarString(Calendar fecha){
        String retorno=null;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (fecha != null) {
        retorno = sdf.format(fecha.getTime());
        }
        return retorno;
}
public String retornarStringHora(Calendar fecha){
        String retorno=null;
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        if (fecha != null) {
        retorno = sdf.format(fecha.getTime());
        }
        return retorno;
}    
public Calendar retornarCalendar(String fecha){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();    
        try {
            cal.setTime(sdf.parse(fecha));
        } catch (ParseException ex) {
          JOptionPane.showMessageDialog(null, "Error; compruebe formato de fecha: " + ex);  
        }
        return cal;
    }
public void eliminar(){
    if(this.jTable1.getSelectedRow()==-1){
      JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila de la tabla.");  
    }
    else{
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminar fila seleccionada.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 0){
            int sel = this.jTable1.getSelectedRow();
            model.removeRow(sel);
            this.idArt.requestFocus();
        }
        else{
            this.idArt.requestFocus();
        }
    }
}
public void guardar(){
    if(this.id.getText().isEmpty() ||this.idClie.getText().isEmpty() ){
        JOptionPane.showMessageDialog(null, "Faltan datos para guardar. Verifique.");
    }
    else{
        if(this.jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No hay datos para guardar.");
        }
        else{
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Desea guardar esta venta.", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
            if(showConfirmDialog == 0){
                try {
                    st.beginTransaction();
                    VentaCab venta = new VentaCab();
                    int idFun = Integer.parseInt(this.id.getText());
                    int idCli = Integer.parseInt(this.idClie.getText());
                    long totalVenta = Long.parseLong(this.totalGeneral.getText());
                    Funcionario funcionario = (Funcionario)st.load(Funcionario.class, idFun);
                    Cliente cliente = (Cliente)st.load(Cliente.class, idCli);
                    Calendar fechaVenta = retornarCalendar(this.fecha.getText());
                    String horaVenta = this.hora.getText();
                    venta.setCliente(cliente);
                    venta.setFuncionario(funcionario);
                    venta.setFecha(fechaVenta);
                    venta.setHora(horaVenta);
                    venta.setTotal(totalVenta);
                    funcionario.getVentaCabs().add(venta);
                    cliente.getVentaCabs().add(venta);
                    int rowCount = this.jTable1.getRowCount();
                    int[] idArti = new int[rowCount];
                    int[] cantVenta = new int[rowCount];
                    for (int i = 0; i < this.jTable1.getRowCount(); i++) {
                        VentaDet detalleVenta = new VentaDet();
                        int idArticulo = Integer.parseInt(String.valueOf(model.getValueAt(i, 0)));
                        idArti[i] = idArticulo;
                        Articulo ventaArticulo = (Articulo)st.load(Articulo.class, idArticulo);
                        int cantidadVenta = Integer.parseInt(String.valueOf(model.getValueAt(i, 3)));
                        cantVenta[i]= cantidadVenta;
                        int importeVenta = Integer.parseInt(String.valueOf(model.getValueAt(i, 4)));
                        detalleVenta.setArticulo(ventaArticulo);
                        detalleVenta.setCant(cantidadVenta);
                        detalleVenta.setImporte(importeVenta);
                        detalleVenta.setVentaCab(venta);
                        venta.getVentaDets().add(detalleVenta);
                    }
                    st.save(venta);
                    st.getTransaction().commit();
                    for (int i = 0; i < idArti.length; i++) {
                        actualizarStrock(cantVenta[i], idArti[i]);
                    }
                    arranque();
                    JOptionPane.showMessageDialog(null, "Venta guardada correctamente.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error guardando venta. Verifique.");
                }
                
            }
            else{                
                this.idArt.requestFocus();
            }
            
        }
    }
}
public void actualizarStrock(int cantidadVendida, int idArticulo){
    st.beginTransaction();
    Articulo actualizar = (Articulo)st.load(Articulo.class, idArticulo);
    int temp = actualizar.getCan() - cantidadVendida;
    actualizar.setCan(temp);
    st.update(actualizar);
    st.getTransaction().commit();
}
}
